# LOOPS IN PYTHON :

In [ ]:
for condition:
    statement1
    statement2
statement3

    

In [1]:
range(0,6)

range(0, 6)

In [2]:
list(range(0,9))

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [3]:
for i in range(0,9):
    print(i)
    print("Hey There")

0
Hey There
1
Hey There
2
Hey There
3
Hey There
4
Hey There
5
Hey There
6
Hey There
7
Hey There
8
Hey There


In [4]:
for i in range(0,9):
    print(i)
print("Hey there")    

0
1
2
3
4
5
6
7
8
Hey there


In [5]:
for i in range(0,9):
    print(i)
    print("hey")
print("There")    

0
hey
1
hey
2
hey
3
hey
4
hey
5
hey
6
hey
7
hey
8
hey
There


In [ ]:
# Let us creating the two lists

In [6]:
stu_name = ["Tom","Karl","Vin","Jeery"]


In [7]:
stu_name

['Tom', 'Karl', 'Vin', 'Jeery']

In [8]:
stu_roll = [101,102,103,104,105]

In [9]:
stu_rol

[101, 102, 103, 104, 105]

In [10]:
stu_course = ["C","C++","Java","R","Python"]

In [11]:
stu_course

['C', 'C++', 'Java', 'R', 'Python']

In [16]:
for (n,r,c) in zip(stu_roll,stu_name,stu_course):
    print(n)
    print("Hey",r,",","welcome to our course",c,"!!!!!!!!!!!!!!!")

101

Hey Tom , welcome to our course C !!!!!!!!!!!!!!!
102

Hey Karl , welcome to our course C++ !!!!!!!!!!!!!!!
103

Hey Vin , welcome to our course Java !!!!!!!!!!!!!!!
104

Hey Jeery , welcome to our course R !!!!!!!!!!!!!!!


In [23]:
emp_name =["Ram","vinit","aisha","Kunal","Laxman"]

In [24]:
emp_id =[1001,1002,1003,1004,1005]

In [25]:
emp_faculty =["AI","Networking","Cyber Security","Data Science","Machine Learning"]

In [26]:
emp_age =[25,36,47,29,33]

In [27]:
emp_salalry =[30000,45000,90000,37000,40000]

In [29]:
for (n,i,f,a,s) in zip(emp_name,emp_id,emp_faculty,emp_age,emp_salalry):
    print("EMPLOYEE ID:",i,"AGE",a)
    print("Hey,Hope You Are Doing Well",n)
    print("Your Alloted Course is",f,"Sallary Wil be",s)
    print("")


EMPLOYEE ID: 1001 AGE 25
Hey,Hope You Are Doing Well Ram
Your Alloted Course is AI Sallary Wil be 30000

EMPLOYEE ID: 1002 AGE 36
Hey,Hope You Are Doing Well vinit
Your Alloted Course is Networking Sallary Wil be 45000

EMPLOYEE ID: 1003 AGE 47
Hey,Hope You Are Doing Well aisha
Your Alloted Course is Cyber Security Sallary Wil be 90000

EMPLOYEE ID: 1004 AGE 29
Hey,Hope You Are Doing Well Kunal
Your Alloted Course is Data Science Sallary Wil be 37000

EMPLOYEE ID: 1005 AGE 33
Hey,Hope You Are Doing Well Laxman
Your Alloted Course is Machine Learning Sallary Wil be 40000



In [30]:
profit = [14000,15000,16000,17000,18000]

In [31]:
sales = [230,560,420,520,630]

In [32]:
# 

profit/sales

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [34]:
profitratio=[]
for i in range(0,len(sales)):
    profitratio.append(profit[i]/sales[i])
    
profitratio    
    

[60.869565217391305,
 26.785714285714285,
 38.095238095238095,
 32.69230769230769,
 28.571428571428573]

# Creating Array:

In [35]:
profit

[14000, 15000, 16000, 17000, 18000]

In [36]:
sales

[230, 560, 420, 520, 630]

In [38]:
import numpy as np

In [39]:
profit_array = np.array(profit)

In [40]:
profit_array

array([14000, 15000, 16000, 17000, 18000])

In [41]:
sales_array = np.array(sales)

In [42]:
sales_array

array([230, 560, 420, 520, 630])

In [43]:
profit_sales_ratio=profit_array/sales_array

In [44]:
profit_sales_ratio

array([60.86956522, 26.78571429, 38.0952381 , 32.69230769, 28.57142857])

In [45]:
list1=[1,"name","id","10.2"]

In [46]:
list1

[1, 'name', 'id', '10.2']

In [47]:
list1_array = np.array(list1)

In [48]:
list1_array

array(['1', 'name', 'id', '10.2'], dtype='<U11')

In [50]:
sales=list1_array.copy()

In [51]:
sales

array(['1', 'name', 'id', '10.2'], dtype='<U11')

In [52]:
sales[1:4]

array(['name', 'id', '10.2'], dtype='<U11')

In [53]:
sales[0]

'1'

In [55]:
sales[3]

'10.2'

# Matrix Creation : it is the collection of arrays element

In [56]:
sales_US = [2000,3000,4000,5000]
sales_UK = [7852,6985,6325,4521]
sales_IN = [789654,456321,123654,789321]

In [58]:
sales_matrix = np.array((sales_US,sales_UK,sales_IN))

In [59]:
sales_matrix

array([[  2000,   3000,   4000,   5000],
       [  7852,   6985,   6325,   4521],
       [789654, 456321, 123654, 789321]])

In [61]:
profit_US = [125,256,325,652]
profit_UK = [125,452,5632,785]
profit_IN =[1236,5632,7854,8965]

In [62]:
profit_matrix = np.array([profit_US,profit_UK,profit_IN])

In [63]:
profit_matrix

array([[ 125,  256,  325,  652],
       [ 125,  452, 5632,  785],
       [1236, 5632, 7854, 8965]])

In [66]:
sales_profit_ratio=sales_matrix/profit_matrix

In [67]:
sales_profit_ratio

array([[ 16.        ,  11.71875   ,  12.30769231,   7.66871166],
       [ 62.816     ,  15.45353982,   1.12304688,   5.75923567],
       [638.87864078,  81.02290483,  15.74407945,  88.0447295 ]])

In [69]:
# create matrix by passing direct values

sales_matrix = np.array(([1,5,6,8],[7,5,9,8],[88,56,98,7]))

In [70]:
sales_matrix

array([[ 1,  5,  6,  8],
       [ 7,  5,  9,  8],
       [88, 56, 98,  7]])

In [71]:
np.reshape(sales_matrix,(3,4),'C')

array([[ 1,  5,  6,  8],
       [ 7,  5,  9,  8],
       [88, 56, 98,  7]])

In [73]:
np.reshape(sales_matrix,(3,4),'F')

array([[ 1,  5,  6,  8],
       [ 7,  5,  9,  8],
       [88, 56, 98,  7]])